name: Continuous Integration - Resuable
on: [workflow_call]
jobs:
  CI_Steps:
    runs-on: [self-hosted]
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - run: echo OK
        name: Code Lint
      #       - run: echo OK..git
      #         name: Code Build
      - run: npm install
        name: Install NodeJS modules
      - run: npm run test:unit
        name: Code Unit Tests
      - run: npm run test:integration

